### ISSUE TITLE
accessCode question

### ISSUE THREAD

**Issue by TCPMeta** [Dilbert66/esphome-vistaECP#1]
In the VistaAlarm.yaml file on line 4 it has a Secrets file for accessCode. Is the Access Code the Installer Code or the Admin User of the Panel for user slot 802? Or can it be any valid user code on the Panel?

**Comment by Dilbert66** [comment]
This is any valid code that can arm  the system.    It is used when an arm command is sent from home assistant but no code is specified (empty string)  so it will use the stored one. Basically a quick arm.   For disarming though, a code must always be sent .
