### ISSUE TITLE
Found some more icache_ram_attr compile warnings.

### ISSUE THREAD

**Issue by XD36JD2015** [Dilbert66/esphome-vistaECP#101]
Found icache_ram_attr compile errors in vista.h.  They can be found on lines 131, 191, 195, & 200.  I replaced these with iram_attr like you did in other places of the code and was able to compile the project without any warnings.

**Comment by Dilbert66** [comment]
I don't compile with the esp8266 too often so don't normally see the warnings. But tks. I've pushed an updated version.

**Comment by XD36JD2015** [comment]
No problem at all.  Thanks for your work on this project.
