### ISSUE TITLE
polymer depreciated

### ISSUE THREAD

**Issue by jakejakejakejakejakejake** [Dilbert66/esphome-vistaECP#104]
As an FYI, polymer was depreciated. This breaks the custom keypad.

https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

Just wanted to others know.

You will see `Uncaught ReferenceError: Polymer is not defined` in browser console.

**Comment by Dilbert66** [comment]
Use the latest version in dev branch of the script

**Comment by jakejakejakejakejakejake** [comment]
I will try that tonight thank you!

**Comment by MihaT2021** [comment]
I get in HA dashbord
Error from custom card
r.setConfig  is not  a funcion

**Comment by Dilbert66** [comment]
Read my comment above.

**Comment by jakejakejakejakejakejake** [comment]
> I will try that tonight thank you!

Many nights later, I tried, and it worked. Many more nights later I am here to close this issue.
