### ISSUE TITLE
Vista 50P Compatability

### ISSUE THREAD

**Issue by gropplerzorn** [Dilbert66/esphome-vistaECP#127]
@Dilbert66 Do you know if this has any potential of working with a Vista 50P alarm panel? Everything looks physically compatible, but I am unsure if the 50P communicates in a different fashion than the 20P panel.

**Comment by Dilbert66** [comment]
Yes, it works fine with the vista50p.  The 50p also supports polling loops which are not directly accessible by the esp code but the zone statuses will still be accessible via the panel statuses.
