### ISSUE TITLE
VistaAlarm.yaml needs updates to ota: and safe_mode: keys

### ISSUE THREAD

**Issue by kschlichter** [Dilbert66/esphome-vistaECP#134]
I'm not entirely sure if this is correct so I'm not opening a pull request.  During the install phase, during the "download project" step I was getting the following error:
```
INFO ESPHome 2024.9.2
INFO Reading configuration /config/VistaAlarm.yaml...
Failed config

ota.unknown: [source /config/VistaAlarm.yaml:141]
  
  'ota' requires a 'platform' key but it was not specified.
  password: !secret ota_password
  safe_mode: 
    disabled: False
  on_begin: 
    switch.turn_off: connection_status_switch
```
I seem to have resolved it by adding `platform: esphome` to the `ota:` key and moving `safe_mode: true` to be its own key:
```
ota:
   platform: esphome ### new
   password: !secret ota_password
   on_begin:
          switch.turn_off: connection_status_switch

safe_mode:
  disabled: false
```

It won't compile for me, so this may be the wrong thing but I'll two issues in case they're separate.

**Comment by Dilbert66** [comment]
That change is correct. The compile is another issue.
