### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by subseaalex** [Dilbert66/esphome-vistaECP#6]
Thank you for the code.
Could you please explain how to get sensor ids? I see in debug, I am reading all my sensors and correct names, however, they are all in hex. 
How do I add them to templates without knowing which z1, z2 etc?
For example, if I have "Living room motion sensor 35" installed, how do I know which id is this? Is it Z35?

Regards,

**Comment by Dilbert66** [comment]
The id is the zone that the sensor belongs to.

**Comment by subseaalex** [comment]
Thank you for quick reply. And how do I know which sensor belongs to which zone?

**Comment by Dilbert66** [comment]
That's part of your panel programming. When you assign your sensors, you assign it to a zone.   You can also just trigger your sensor and see which is showing on your keypad display as open.

**Comment by subseaalex** [comment]
We have converted all wired sensors to wireless with receiver SA5881-6NECR. Its wired to vista21iP.
It is not default installed code. I cant check the zones.
For example when I trigger door, the panel displays "Fault 29 Garage Entry" Does it means its zone29?

**Comment by Dilbert66** [comment]
Yes, 29 would be the zone

**Comment by subseaalex** [comment]
Thank you kindly. I undestand now. I have to add case id with the zone, and use id in template. 
It is working now. Thanks for all your help.
