### ISSUE TITLE
Status LED documentation

### ISSUE THREAD

**Issue by jsbrich** [Dilbert66/esphome-vistaECP#62]
In the ESPHome yaml file, there is a section commented out for the Status LED.  Is there anything written down for what that led does?

**Comment by Dilbert66** [comment]
Here you go: 
https://esphome.io/components/status_led.html

**Comment by jsbrich** [comment]
Ah, so it's a general ESPHome thing, not specifc to this project.  I had it at GPIO2, and ESPHome gave me the warning about GPIO2 being a strapping pin, so I moved it to GPIO16.  It seems to work fine, it was blinking rapidly for me, but that's likely cuz I don't have this hooked up to my alarm system yet.
