### ISSUE TITLE
'ARMED' was not declared in this scope

### ISSUE THREAD

**Issue by AlexandreUSA** [Dilbert66/esphome-vistaECP#71]
Using the latest files, I am getting the following error:

`In file included from src/main.cpp:76:0:
src/vistaAlarm.h: In member function 'virtual void esphome::vistaECPHome::update()':
src/vistaAlarm.h:799:28: error: 'ARMED' was not declared in this scope
             if (strstr(p1, ARMED) && vista.statusFlags.systemFlag) {
                            ^`

Going back to older files, the error disapears.

**Comment by Dilbert66** [comment]
Fixed.

**Comment by AlexandreUSA** [comment]
Fixed confirmed. Thank you !
