### ISSUE TITLE
Bug Report: Zone Names Interpreted as Status

### ISSUE THREAD

**Issue by rcmurphy** [Dilbert66/esphome-vistaECP#87]
I have a zone named `Alarm Cabinet Door`. When bypassing this zone, the ESPHome sees `BYPAS 004 ALARM CABINET DOOR`  and assumes the system is alarming.

**Comment by Dilbert66** [comment]
Ahhh. Yes I'll correct that . Regex tweak.

**Comment by Dilbert66** [comment]
Fix applied and pushed to dev.

**Comment by rcmurphy** [comment]
❤️ Thank you so much!

**Comment by Dilbert66** [comment]
I've pushed a new update that replaces the regex prompt search for a custom for/loop function to speed things.  The regex added way too many cycles in the loop.

**Comment by Dilbert66** [comment]
I'll close this as this should be good now.
